### ISSUE TITLE
build with last recent gradle

### ISSUE THREAD

**Issue by minooei** [leadrien/opencv_native_androidstudio#1]
Hi there
I love your work here and thank you for sharing it.
I follow your instruction and succeed to compile with this configuration:
opencv 3.1
gradle-experimental:0.7.0-alpha4
sdk 23
just one tip for this instruction:
fully read this [http://tools.android.com/tech-docs/new-build-system/gradle-experimental](url) to config gradle properly.
cheers.

**Comment by leadrien** [comment]
Hi,
Thank you for your advice.
I have just refactor the whole project to work with Android Studio 2.2
Have a look it is way simpler, and no need for experimental gradle anymore.
Regards
