### ISSUE TITLE
How do we make symlink ?

### ISSUE THREAD

**Issue by mohitsingh9512** [leadrien/opencv_native_androidstudio#10]

**Comment by Bastl34** [comment]
Like this:
`ln -s YOUR_OPENCV_ANDROID_SDK/sdk/native/libs jniLibs`

**Comment by hollaus** [comment]
Under windows use [mklink](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink). Using a simple shortcut is not sufficient.
