### ISSUE TITLE
The software does not work as delivery

### ISSUE THREAD

**Issue by cxjacquel** [leadrien/opencv_native_androidstudio#12]
Hello, 
When I try to run the Android App, I have this message : 
Build command failed.
Error while executing process C:\Users\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\Users\Desktop\opencv_native_androidstudio-master\opencv_native_androidstudio-master\app\.externalNativeBuild\cmake\debug\x86 --target native-lib}
ninja: error: '../../../../src/main/jniLibs/x86/libopencv_java3.so', needed by '../../../../build/intermediates/cmake/debug/obj/x86/libnative-lib.so', missing and no known rule to make it

Could you help ? 
Thank you,
Christophe

**Comment by leadrien** [comment]
Looks like you failed the symlink step.
Try to copy the `YOUR_OPENCV_SDK/sdk/native/libs` folder content into `app/src/main/jniLibs`
