### ISSUE TITLE
Rotated camera Image

### ISSUE THREAD

**Issue by sebasira** [leadrien/opencv_native_androidstudio#2]
Hello! Thanks for sharing this and making the Usage guide. I've manage to compile and test your code, but the only problem I'm facing is that screen image is rotated 90° (non clockwise). Any idea of what's going on?

Thanks in advance!

PS: I'm using a Moto G 1st gen

**Comment by leadrien** [comment]
Hi, 
Thank you for pointing this out.
This app was meant to run in landscape mode.
Cheers

**Comment by sebasira** [comment]
And do you know a way to change this? No matter how I turn the phone, it's always rotated. I've done another sample without NDK and camera orientation is ok.

I've read a lot a stackoverflow solutions but they all seem kind of 'dirty'. Thank you!

**Comment by leadrien** [comment]
You still have the problem with the revision I pushed this morning? f2ae548

**Comment by sebasira** [comment]
I've added that diff and now it works in landscape as you pointed. but I want the app to work in portrait.

I don't know if it's related to NDK because as I said, I've got another simple example that only shows the camera preview using CameraBridgeView and works in any orientation.

**Comment by sebasira** [comment]
Taking a closer look to the sample I mentioned, I found out that it was using a fullscreen theme, so there were no ActionBar and I think it was working in any orientation, but it was in landscape just like yours.

Sorry! And thank you for your replies!
