### ISSUE TITLE
Not able to understand step "Make a symlink named jniLibs in app/src/main that points to YOUR_OPENCV_SDK/sdk/native/libs" can you please help me. Its not issue

### ISSUE THREAD

**Issue by asbadve** [leadrien/opencv_native_androidstudio#7]

**Comment by leadrien** [comment]
On which operating system are you?

**Comment by asbadve** [comment]
I got it... thanks...sorry I forgot to close

**Comment by mohitsingh9512** [comment]
How did you solve it  ?

**Comment by mohammedmatar** [comment]
@mohitsingh9512 
linux and mac
`ln -s "your source" "your destentation"` i think so.
on windows
`mklink Link Target`
