### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by Sakthivel-bpigt** [leadrien/opencv_native_androidstudio#8]
Hi,
I want to work on OpenCV with native C++ and trying to build your project.
i have encountered a cmake build problem.
I think its a simple problem but i still couldn't figure out, maybe you might have an idea.

 What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process C:\Users\sakthivel\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build D:\OCVA\opencv_native_androidstudio-master\opencv_native_androidstudio-master\app\.externalNativeBuild\cmake\debug\arm64-v8a --target native-lib}
  ninja: error: '../../../../src/main/jniLibs/arm64-v8a/libopencv_java3.so', needed by '../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libnative-lib.so', missing and no known rule to make it

**Comment by leadrien** [comment]
Hello,
It may be a problem with the jniLibs symlink. As you are on windows you should try to copy the entire OPENCV_SDK/sdk/native/libs directory into app/src/main/jniLibs.

So when you browse into app/src/main/jniLibs, you see your arm64-v8a directory.

**Comment by Sakthivel-bpigt** [comment]
Hi,
thanks for the advice.
It worked out well.

**Comment by abhigarg** [comment]
yes the symlink is not working on mac. Not sure why
